"""salas table

Revision ID: 25a411254135
Revises: ff8f59517d9b
Create Date: 2018-10-17 09:54:55.560830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a411254135'
down_revision = 'ff8f59517d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.String(length=100), nullable=True),
    sa.Column('hora', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sala_numero'), 'sala', ['numero'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sala_numero'), table_name='sala')
    op.drop_table('sala')
    # ### end Alembic commands ###
