"""salas table

Revision ID: 7d22fcbe7e91
Revises: 25a411254135
Create Date: 2018-10-18 09:32:05.028159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d22fcbe7e91'
down_revision = '25a411254135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sala_numero', table_name='sala')
    op.create_index(op.f('ix_sala_numero'), 'sala', ['numero'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sala_numero'), table_name='sala')
    op.create_index('ix_sala_numero', 'sala', ['numero'], unique=1)
    # ### end Alembic commands ###
